#!/bin/env python3

import sys

if len(sys.argv) != 3:
    print(f"Must invoke as:\n {sys.argv[0]} <in_file> <out_file>")
    exit(1)

in_file = sys.argv[1]
out_file = sys.argv[2]

print(sys.argv[0], f"Generating {in_file} -> {out_file}")

OUT_FILE_START = f"""// DO NOT EDIT THIS FILE
// This file has been generated by read_wav_to_bytes.py
// USING {in_file} as its input
#include <inttypes.h>\n""" 

DATA_START = "static const uint8_t soundWavData[] = {"

OUT_FILE_END = "};\n"

with open(out_file, "w") as out:
    with open(in_file, "rb") as f:
        data = f.read()
        dataLen = len(data)
        out.write(OUT_FILE_START)
        out.write(f"#define SOUND_WAVDATA_LEN {dataLen}\n")
        out.write(DATA_START)
        for i,b in enumerate(data):
            if i % 19 == 0:
                out.write('\n    ')
            out.write(f"{b:>3}") # print exactly 3 characters with potential whitespace to the left
            if i != dataLen -1:
                out.write(', ')
    out.write(OUT_FILE_END)
