name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**/*
      - scripts/**/*
      - test/**/*
      - CMakeLists.txt
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**/*
      - scripts/**/*
      - test/**/*
      - CMakeLists.txt

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install libsfml-dev
    - name: configure build 
      run: cmake -B build
    - name: run build
      run: cmake --build build
    - name: run tests
      run: ./build/clock.test && ./build/duration-parser.test
